### ISSUE TITLE
Issue: internal link should have an anchor text

### ISSUE THREAD

**Issue by paavo** [jonnitto/Jonnitto.OutdatedBrowser#1]
**Problem**
`<a href="#" id="btnCloseUpdateBrowser"...`
> Has an internal link with no anchor text

**Solution**
Add an anchor
`<a href="#close" id="btnCloseUpdateBrowser"...`

Should be fixed in all Languages 🙈  Too much for a simple PR. 
https://github.com/jonnitto/Jonnitto.OutdatedBrowser/blob/master/Resources/Private/Templates/de.html

**Comment by jonnitto** [comment]
Thank you for the hint. I'll update it to change the anchor to an button
